config/routes.rb
Rails.application.routes.draw do
  resources :new_features
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/new_feature.rb
class NewFeature < ApplicationRecord
  has_many_attached :images
  # validates :auth_token, uniqueness: true, allow_blank: true
  # has_one_attached :image

  # validate :images?

    private

    # def images?
    #   errors.add(:base, 'Please upload your company logo.') unless images.attached?
    # end

    # def images?
    #   # Clean exit if there is a logo
    #   return if images.attached?

    #   # Unless add error
    #   errors.add(:base, 'Please upload your company logo.')

    #   # Purge the blob
    #   images.record.images_attachments.purge

    #   # Purge attachment
    #   images.purge
    # end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
end

app/controllers/new_features_controller.rb
class NewFeaturesController < ApplicationController
  def index
    @news = NewFeature.all
  end

  def new
    @new_feature = NewFeature.new
  end

  def create
    # @new_feature = NewFeature.create!(new_feature_params)
    @new_feature = NewFeature.new(new_feature_params)
    if !@new_feature.images.attach.blank? == true
      @new_feature.images.attach(params[:new_feature][:images])
      @new_feature.save
      redirect_to new_features_path
      flash[:notice] = "News Blog was successfully created!"
      # @new_feature_images = @new_feature.images.attach(params[:new_feature][:images])
      # @new_feature_images.save
    else
      @new_feature.save
      redirect_to new_features_path
      flash[:notice] = "News Blog was successfully created!"
    end
  end

  def show
    @new_feature = NewFeature.find(params[:id])
  end

  def edit
    @new_feature = NewFeature.find(params[:id])
  end

  def update
    @new_feature = NewFeature.find(params[:id])
    if @new_feature.update(new_feature_params)
      flash[:notice] = "News Blog successfully updated!"
    end
  end

  def destroy
    @new_feature = NewFeature.find(params[:id])
    if @new_feature.destroy
      redirect_to new_features_path
      flash[:notice] = "News Blog was successfully deleted!"
    end
  end

  private

  def new_feature_params
    params.require(:new_feature).permit(:title, :text, images: [])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:home]

  def home
    @news = NewFeature.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>TODO</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%#= stylesheet_pack_tag 'application', media: 'all' %> <!-- Uncomment if you import CSS in app/javascript/packs/application.js -->
  </head>
  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>
    <%= yield %>
    <%= javascript_include_tag 'application' %>
    <%#= javascript_pack_tag 'application' %>
  </body>
</html>

app/views/new_features/_news_form.html.erb
<div class="container">
  <div class="row">
    <h1 class="text-center" style="color:#445d77;">Add to your News Blog</h1>
    <div class="col-xs-12">
      <%= simple_form_for @new_feature do |form| %>
      <%#= form_with model: @new_feature, local: true do |form| %>
        <%= form.input :title %>
        <%= form.input :text %>
        <%= form.input :images, as: :file, input_html: { multiple: true } %>
        <br>
        <%= form.submit "Add To News", class: 'btn btn-primary' %>
      <% end %>
    </div>
  </div>
</div>


<style>
  body {
    background-color: #fff;
  }

  .row {
    margin-top:35px;
    box-shadow:5px 5px 25px 0px #778899 ;
    padding-bottom: 25px;
  }

  .new_feature_title, .new_feature_text, .new_feature_title input, .new_feature_text input, .new_feature_images {
    color:#445d77;
  }

  input {
    color:#778899;
  }

</style>

app/views/new_features/create.html.erb
<h1>NewFeatures#create</h1>
<p>Find me in app/views/new_features/create.html.erb</p>

app/views/new_features/edit.html.erb
<%= render partial: "news_form" %>

app/views/new_features/index.html.erb
<div class="parallax1">
  <div class="banner">
  <div class="banner-content text-center">
    <h1>Caremeds News & Updates</h1>
    <br>
    <p>Our main focus is on helping you helping others and that is why we would love to share several of our resources, tips and information about our Solutions across the entire stack.</p>
  </div>
  </div>
</div>

<div class="container">
  <div class="row">
    <div class="col-xs-12">
      <% @news.each do |nf| %>
        <%= link_to new_feature_path(nf) do %>
          <div class="news-item">
            <div class="title">
              <div class="news-date">
                <p class="created-day"><%= nf.created_at.strftime("%e") %></p>
                <p class="created-month"><%= nf.created_at.strftime("%b") %></p>
              </div>
                <h2 style="color:#445d77"><%= nf.title %></h2>
            </div>
            <hr style="border-color:#9d9d9d6b;margin:8px 0 8px 0;">
            <p class="news-info">Details</p>
            <p style="color:#778899"><%= nf.text %></p>
            <div class="row">
              <% counter = 0 %>
              <% if nf.images.attachments != nil %>
                <% nf.images.each do |i| %>
                <% counter += 1 %>
                 <div class="-col-xs-12 col-sm-4 pad-bot">
                  <div class="card-<%= counter %>">
                    <div class="card-image">
                      <%= image_tag i %>
                    </div>
                  </div>
                 </div>
                <% end %>
              <% end %>
            </div>
          </div>
        <% end %>
      <% end %>
    </div>
  </div>
</div>


<style>
  body {
    background-color:#fff;
  }

  .parallax1 {
    /* Set a specific height */
    // height: 550px;

    /* Create the parallax scrolling effect */
    background-attachment: fixed;
    background-position: center;
    background-repeat: no-repeat;
    background-size: cover;
  }

  .parallax1 {
    background-image: linear-gradient(-225deg, rgba(0,101,168,0.6) 0%, rgba(0,36,61,0.6) 50%), url("https://cdn.pixabay.com/photo/2017/06/29/14/54/umbrella-2454454_960_720.jpg");
  }

  .banner {
    display: flex;
    align-items: center;
    justify-content: space-around;
    height:500px;
  }

  .banner-content {
    width:50%;
    margin:60px;
    color:white;
  }

  .news-item  {
    border-bottom: 1px solid grey;
    margin-top:25px;
    margin-bottom:50px;
  }

  .title {
    display: flex;
  }

  .news-date {
    /*display: flex;*/
    /*flex-direction: column;*/
    /*border-right: 1px solid red;*/
    padding: 12px 15px;
    margin: 0px 15px 6px 0px;
    background: #1c60ad;
    border: 1px solid #2c97d2;
    color: white;
    border-radius: 10px;
  }

  .created-month {
    letter-spacing: 2px;
    text-align: center;
    font-size: 10px;
    text-transform: uppercase;
    line-height: 14px;
  }

  .created-day {
    font-size: 27px;
    letter-spacing: 0;
    text-align: center;
    line-height: 30px;
  }

  .news-info {
    /*display: inline;*/
    padding: 0px 12px;
    /*margin-right: 10px;*/
    /*background: #f5f5f5;*/
    /*background: #666;*/
    background: #778899;
    line-height: 24px;
    font-size: 10px;
    /*color: #666;*/
    color: white;
    text-transform: uppercase;
    font-weight: bold;
    opacity:0.5;
  }

  .pad-bot {
    padding-bottom: 10px;
  }

  .card-1,.card-2,.card-3,.card-4,.card-5,.card-6,.card-7,.card-8,.card-9 {
    background-color: white;
    box-shadow: 0px 5px 20px #555;
    margin-top: 20px;
    margin-bottom: 10px;
    position: relative;
  }

  .card-image {
    height: 200px;
    position: relative;
    overflow: hidden;
  }

  .card-image img {
    max-width: 100%;
    height:100%;
    position: absolute;
    top: 50%;
    left: 50%;
    transform: translate(-50%, -50%);
    filter: grayscale(1);
    transition-property: filter width;
    transition-duration: .3s;
    // opacity: 0.8;
  }

  .card-1:hover,.card-4:hover,.card-7:hover {
    visibility: visible;
    opacity: 1;
    transform:scale(3,3);
    transform-origin: left;
    z-index:100;
    .card-image img {filter: grayscale(0);}
  }

  .card-2:hover,.card-5:hover,.card-8:hover {
    visibility: visible;
    opacity: 1;
    transform:scale(3,3);
    z-index:100;
    .card-image img {filter: grayscale(0);}
  }

  .card-3:hover,.card-6:hover,.card-9:hover {
    visibility: visible;
    opacity: 1;
    transform:scale(3,3);
    transform-origin: right;
    z-index:100;
    .card-image img {filter: grayscale(0);}
  }


</style>

app/views/new_features/new.html.erb
<div class="container">
  <div class="row">
    <h1 class="text-center" style="color:#445d77;">Add to your News Blog</h1>
    <div class="col-xs-12">
      <%= simple_form_for @new_feature do |form| %>
      <%#= form_with model: @new_feature, local: true do |form| %>
        <%= form.input :title %>
        <%= form.input :text %>
        <%= form.input :images, as: :file, input_html: { multiple: true } %>
        <br>
        <%= form.submit "Add To News", class: 'btn btn-primary' %>
      <% end %>
    </div>
  </div>
</div>


<style>
  body {
    background-color: #fff;
  }

  .row {
    margin-top:35px;
    box-shadow:5px 5px 25px 0px #778899 ;
    padding-bottom: 25px;
  }

  .new_feature_title, .new_feature_text, .new_feature_title input, .new_feature_text input, .new_feature_images {
    color:#445d77;
  }

  input {
    color:#778899;
  }

</style>

app/views/new_features/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-12">
        <div class="news-item">
          <div class="title">
            <div class="news-date">
              <p class="created-day"><%= @new_feature.created_at.strftime("%e") %></p>
              <p class="created-month"><%= @new_feature.created_at.strftime("%b") %></p>
            </div>
              <h2 id="nf-title"><%= @new_feature.title %></h2>
              <p><%= link_to "Edit", edit_new_feature_path(@new_feature) %></p>|
              <p><%= link_to "Delete", new_feature_path(@new_feature), method: :delete, data: { confirm: "Are You Sure?"} %></p>
          </div>
          <hr style="border-color:#9d9d9d6b;margin:8px 0 8px 0;">
          <p class="news-info">Details</p>
          <p style="color:#778899"><%= @new_feature.text %></p>
          <div class="row" style="padding-bottom: 20px">
            <% counter = 0 %>
            <% if @new_feature.images.attachments != nil %>
              <% @new_feature.images.each do |i| %>
              <% counter += 1 %>
               <div class="-col-xs-12 col-sm-4">
                <div class="card-<%= counter %>">
                  <div class="card-image">
                    <%= image_tag i %>
                  </div>
                </div>
               </div>
              <% end %>
            <% end %>
          </div>
        </div>
    </div>
  </div>
</div>


<style>
  body {
    background-color:#fff;
  }

  .news-item  {
    border-bottom: 1px solid grey;
    margin-top:50px;
    margin-bottom:30px;
  }

  .title {
    display: flex;
    justify-content: space-between;
  }

  #nf-title {
    /*position: absolute;
    left: 100px;*/
    flex-grow: 2;
    color:#445d77;
  }

  .news-date {
    /*display: flex;*/
    /*flex-direction: column;*/
    /*border-right: 1px solid red;*/
    padding: 12px 15px;
    margin: 0px 15px 6px 0px;
    background: #1c60ad;
    border: 1px solid #2c97d2;
    color: white;
    border-radius: 10px;
  }

  .created-month {
    letter-spacing: 2px;
    text-align: center;
    font-size: 10px;
    text-transform: uppercase;
    line-height: 14px;
  }

  .created-day {
    font-size: 27px;
    letter-spacing: 0;
    text-align: center;
    line-height: 30px;
  }

  .news-info {
    /*display: inline;*/
    padding: 0px 12px;
    /*margin-right: 10px;*/
    /*background: #f5f5f5;*/
    /*background: #666;*/
    background: #778899;
    line-height: 24px;
    font-size: 10px;
    /*color: #666;*/
    color: white;
    text-transform: uppercase;
    font-weight: bold;
    opacity:0.5;
  }

  .card-1,.card-2,.card-3,.card-4,.card-5,.card-6,.card-7,.card-8,.card-9 {
    background-color: white;
    box-shadow: 0px 5px 20px #555;
    margin-top: 20px;
    margin-bottom: 10px;
    position: relative;
  }

  .card-image {
    height: 200px;
    position: relative;
    overflow: hidden;
  }

  .card-image img {
    width: 100%;
    height:100%;
    position: absolute;
    top: 50%;
    left: 50%;
    transform: translate(-50%, -50%);
    filter: grayscale(1);
    transition-property: filter width;
    transition-duration: .3s;
    // opacity: 0.8;
  }

  .card-1:hover,.card-4:hover,.card-7:hover {
    visibility: visible;
    opacity: 1;
    transform:scale(3,3);
    transform-origin: left;
    z-index:100;
    .card-image img {filter: grayscale(0);}
  }

  .card-2:hover,.card-5:hover,.card-8:hover {
    visibility: visible;
    opacity: 1;
    transform:scale(3,3);
    z-index:100;
    .card-image img {filter: grayscale(0);}
  }

  .card-3:hover,.card-6:hover,.card-9:hover {
    visibility: visible;
    opacity: 1;
    transform:scale(3,3);
    transform-origin: right;
    z-index:100;
    .card-image img {filter: grayscale(0);}
  }


</style>

app/views/pages/home.html.erb
<div class="parallax1">
  <div class="banner">
  <div class="banner-content text-center">
    <h1>Caremeds News & Updates</h1>
    <br>
    <p>Our main focus is on helping you helping others and that is why we would love to share several of our resources, tips and information about our Solutions across the entire stack.</p>
  </div>
  </div>
</div>

<div class="container">
  <div class="row">
    <div class="col-xs-12">
      <% @news.each do |nf| %>
          <div class="news-item">
            <div class="title">
              <div class="news-date">
                <p class="created-day"><%= nf.created_at.strftime("%e") %></p>
                <p class="created-month"><%= nf.created_at.strftime("%b") %></p>
              </div>
                <h2 style="color:#445d77"><%= nf.title %></h2>
            </div>
            <hr style="border-color:#9d9d9d6b;margin:8px 0 8px 0;">
            <p class="news-info">Details</p>
            <p style="color:#778899"><%= nf.text %></p>
            <div class="row">
              <% counter = 0 %>
              <% if nf.images.attachments != nil %>
                <% nf.images.each do |i| %>
                <% counter += 1 %>
                 <div class="-col-xs-12 col-sm-4 pad-bot">
                  <div class="card-<%= counter %>">
                    <div class="card-image">
                      <%= image_tag i %>
                    </div>
                  </div>
                 </div>
                <% end %>
              <% end %>
            </div>
          </div>
      <% end %>
    </div>
  </div>
</div>


<style>
  body {
    background-color:#fff;
  }

  .parallax1 {
    /* Set a specific height */
    // height: 550px;

    /* Create the parallax scrolling effect */
    background-attachment: fixed;
    background-position: center;
    background-repeat: no-repeat;
    background-size: cover;
  }

  .parallax1 {
    background-image: linear-gradient(-225deg, rgba(0,101,168,0.6) 0%, rgba(0,36,61,0.6) 50%), url("https://cdn.pixabay.com/photo/2017/06/29/14/54/umbrella-2454454_960_720.jpg");
  }

  .banner {
    display: flex;
    align-items: center;
    justify-content: space-around;
    height:500px;
  }

  .banner-content {
    width:50%;
    margin:60px;
    color:white;
  }

  .news-item  {
    border-bottom: 1px solid grey;
    margin-top:25px;
    margin-bottom:50px;
  }

  .title {
    display: flex;
  }

  .news-date {
    /*display: flex;*/
    /*flex-direction: column;*/
    /*border-right: 1px solid red;*/
    padding: 12px 15px;
    margin: 0px 15px 6px 0px;
    background: #1c60ad;
    border: 1px solid #2c97d2;
    color: white;
    border-radius: 10px;
  }

  .created-month {
    letter-spacing: 2px;
    text-align: center;
    font-size: 10px;
    text-transform: uppercase;
    line-height: 14px;
  }

  .created-day {
    font-size: 27px;
    letter-spacing: 0;
    text-align: center;
    line-height: 30px;
  }

  .news-info {
    /*display: inline;*/
    padding: 0px 12px;
    /*margin-right: 10px;*/
    /*background: #f5f5f5;*/
    /*background: #666;*/
    background: #778899;
    line-height: 24px;
    font-size: 10px;
    /*color: #666;*/
    color: white;
    text-transform: uppercase;
    font-weight: bold;
    opacity:0.5;
  }

  .pad-bot {
    padding-bottom: 10px;
  }

  .card-1,.card-2,.card-3,.card-4,.card-5,.card-6,.card-7,.card-8,.card-9 {
    background-color: white;
    box-shadow: 0px 5px 20px #555;
    margin-top: 20px;
    margin-bottom: 10px;
    position: relative;
  }

  .card-image {
    height: 200px;
    position: relative;
    overflow: hidden;
  }

  .card-image img {
    max-width: 100%;
    height:100%;
    position: absolute;
    top: 50%;
    left: 50%;
    transform: translate(-50%, -50%);
    filter: grayscale(1);
    transition-property: filter width;
    transition-duration: .3s;
    // opacity: 0.8;
  }

  .card-1:hover,.card-4:hover,.card-7:hover {
    visibility: visible;
    opacity: 1;
    transform:scale(3,3);
    transform-origin: left;
    z-index:100;
    .card-image img {filter: grayscale(0);}
  }

  .card-2:hover,.card-5:hover,.card-8:hover {
    visibility: visible;
    opacity: 1;
    transform:scale(3,3);
    z-index:100;
    .card-image img {filter: grayscale(0);}
  }

  .card-3:hover,.card-6:hover,.card-9:hover {
    visibility: visible;
    opacity: 1;
    transform:scale(3,3);
    transform-origin: right;
    z-index:100;
    .card-image img {filter: grayscale(0);}
  }


</style>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar-wagon">
  <!-- Logo -->
  <%= link_to root_path, class: "navbar-wagon-brand" do %>
    <%= image_tag "cms-logo.png", height: 150 %>
  <% end %>

  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">

    <% if user_signed_in? %>

      <!-- Links when logged in -->
      <%= link_to "New Blog", new_new_feature_path, class: "navbar-wagon-item navbar-wagon-link" %>
      <%= link_to "All Blogs", new_features_path, class: "navbar-wagon-item navbar-wagon-link" %>
      <%#= link_to "Messages", "#", class: "navbar-wagon-item navbar-wagon-link" %>

      <!-- Avatar with dropdown menu -->
      <div class="navbar-wagon-item">
        <div class="dropdown">
          <%= image_tag "https://png.icons8.com/ios/100/5A6064/circled-#{current_user.email[0]}.png", class: "avatar dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>
          <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
            <li>
              <%= link_to edit_user_registration_path do %>
                <i class="fa fa-user"></i> <%= t(".profile", default: "Profile") %>
              <% end %>
            </li>
            <!-- <li>
              <%#= link_to "#" do %>
                <i class="fa fa-cog"></i>  <%#= t(".settings", default: "Settings") %>
              <%# end %>
            </li> -->
            <li>
              <%= link_to destroy_user_session_path, method: :delete do %>
                <i class="fa fa-sign-out"></i>  <%= t(".sign_out", default: "Log out") %>
              <% end %>
            </li>
          </ul>
        </div>
      </div>
    <% else %>
      <!-- Login link (when logged out) -->
      <%= link_to t(".sign_in", default: "Login"), new_user_session_path, class: "navbar-wagon-item navbar-wagon-link" %>
    <% end %>
  </div>

  <!-- Dropdown list appearing on mobile only -->
  <div class="navbar-wagon-item hidden-md hidden-lg">
    <div class="dropdown">
      <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
        <li><%= link_to "New Blog", new_new_feature_path, class: "navbar-wagon-item navbar-wagon-link" %></li>
        <li><%= link_to "All Blogs", new_features_path, class: "navbar-wagon-item navbar-wagon-link" %></li>
      </ul>
    </div>
  </div>
</div>